// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABE0Rx-ViGcKCHA5oh7bQGzkbayobsyYs',
    appId: '1:1069842051069:web:bc4eef875ad4d35b5c7394',
    messagingSenderId: '1069842051069',
    projectId: 'festcine-pedra-azul-a267e',
    authDomain: 'festcine-pedra-azul-a267e.firebaseapp.com',
    storageBucket: 'festcine-pedra-azul-a267e.appspot.com',
    measurementId: 'G-2DML4MQP98',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_qED_llYmhCkBUzPkEQAxJhPY6Qm_0t0',
    appId: '1:1069842051069:android:c67fb3718d7e7b825c7394',
    messagingSenderId: '1069842051069',
    projectId: 'festcine-pedra-azul-a267e',
    storageBucket: 'festcine-pedra-azul-a267e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLs_l-6g3BodUjDED__GkLc8j5VfdIDUg',
    appId: '1:1069842051069:ios:305d1b381d0fac995c7394',
    messagingSenderId: '1069842051069',
    projectId: 'festcine-pedra-azul-a267e',
    storageBucket: 'festcine-pedra-azul-a267e.appspot.com',
    iosBundleId: 'com.example.pedraazulApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLs_l-6g3BodUjDED__GkLc8j5VfdIDUg',
    appId: '1:1069842051069:ios:66dae37cd41104db5c7394',
    messagingSenderId: '1069842051069',
    projectId: 'festcine-pedra-azul-a267e',
    storageBucket: 'festcine-pedra-azul-a267e.appspot.com',
    iosBundleId: 'com.example.pedraazulApp.RunnerTests',
  );
}
